# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  {% for item in deprecated %}

  review_deprecated_component_{{ item.name }}:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: {{ colors.red if (item.rating == 'E' or item.rating == 'D') else (colors.orange if (item.rating == 'C' ) else colors.yellow) }}
  {% endfor %}

sources:
 branch: {{ branch.name | includes(term="feature") }}
 path:  {{ files | match(regex=r/^docs\/changelog\.md$/) }}

# These are the deprecated files that are evaluated in catch_deprecated_components
labels:
  - name: Core
    resources:
    - src/app
    branch: r/^core-/
  - name: mobile
    resources:
    - src/android
    - src/ios
    branch: r/^mobile-/
