# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  # Request changes when a PR includes deprecated components.
  # This requires the `item` custom expression found at the bottom of this file.
  {% for item in deprecated %}
  # Automation names must be unique, so this adds an iterator index to each instance
  review_deprecated_component_{{ item.old }}:
    # Triggered when any of the modified files use a deprecated component
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: 'deprecated-component'
          color: '#FF0000'
  {% endfor %}

# These are the deprecated files that are evaluated in catch_deprecated_components
labels:
  - name: Core
    resources:
    - src/app
    branch: r/^core-/
  - name: mobile
    resources:
    - src/android
    - src/ios
    branch: r/^mobile-/
