apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  namespace: earthly
spec:
  containers:
  - name: app
    image: gcr.io/google-samples/gb-frontend:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "100m"
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20