apiVersion: v1
kind: Pod
metadata:
  name: pod-dev
  namespace: development
spec:
  serviceAccountName: development-serviceaccount
  containers:
  - name: app
    image: portainer/portainer-ee:latest
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20